ca: .
opsec: true

server:
  grpc_port: 5004
  grpc_host: 127.0.0.1
  config:
    packet_length: 1048576 # 1M

listeners:
  server_addr: 127.0.0.1:5004
  tcp:
    - name: tcp_default
      port: 5001
      host: 0.0.0.0
      protocol: tcp
      enable: true